name: Release

on:
  push:
    # tags:
    #   - 'v*'
    branches:
      - master
      - gh-actions

jobs:
  build:
    name: Build and release binaries
    # TODO: ubuntu-24.04-arm
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     target:
    #       - x86_64-unknown-linux-gnu
    #       - x86_64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Install Rust target
      #   run: rustup target add ${{ matrix.target }}

      - name: Build binary
        # run: cargo build --release --target=${{ matrix.target }}
        run: cargo build --release

      - name: Package
          # llvm-strip target/${{ matrix.target }}/release/gptfeed
          # cp target/${{ matrix.target }}/release/gptfeed dist/
          # zip ${GITHUB_REPOSITORY##*/}-${{ matrix.target }}.zip gptfeed
        run: |
          mkdir dist
          llvm-strip target/release/gptfeed
          cp target/release/gptfeed dist/
          cd dist
          zip ${GITHUB_REPOSITORY##*/}.zip gptfeed

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
